<script lang="ts" module>
    export { default as layout } from '@/layouts/dashboard.svelte';
</script>

<script lang="ts">
    import QRCode from 'qrcode';
    import { useForm } from '@/inertia';
    import * as InputOTP from '$lib/components/ui/input-otp';
    import { REGEXP_ONLY_DIGITS } from 'bits-ui';
    import { Label } from '$lib/components/ui/label';
    import { Input } from '$lib/components/ui/input';
    import FieldError from '$lib/components/FieldError.svelte';
    import { Button } from '$lib/components/ui/button';
    import { loading } from '$lib/loading.svelte';
    import DashboardMain from '$lib/components/DashboardMain.svelte';
    import { first_layer_dropdown } from '$lib/breadcrumbs';

    type _keep = [typeof InputOTP];

    let {
        secret,
        qr,
        debug_code
    }: {
        secret: string;
        qr: string;
        debug_code: string | null;
    } = $props();

    const form = useForm({
        otp: debug_code ?? ''
    });

    const processing = loading.derived(() => form.processing);

    function renderQR(data: string) {
        return new Promise((resolve, reject) => {
            QRCode.toString(
                data,
                {
                    type: 'svg',
                    color: {
                        dark: '#000000',
                        light: '#ffffff'
                    }
                },
                (err, svg) => {
                    if (err) {
                        reject(err);
                    } else {
                        resolve(
                            svg
                                .replace('stroke="#000000"', 'class="stroke-foreground"')
                                .replace('fill="#ffffff"', 'class="fill-background"')
                        );
                    }
                }
            );
        });
    }
</script>

<DashboardMain
    title="Setup 2FA"
    breadcrumbs={[
        {
            label: 'Profile',
            dropdown: first_layer_dropdown('profile')
        },
        { label: '2FA' },
        { label: 'Setup', href: '/2fa/setup' }
    ]}
>
    <div class="w-full min-h-full flex items-center justify-center px-4 py-2">
        <div
            class="grid grid-rows-[auto,auto] grid-cols-1 @[1024px]:grid-rows-1 @[1024px]:grid-cols-[auto,1fr] max-w-screen-md gap-4"
        >
            <div class="mx-auto">
                <div class="w-[300px] aspect-square">
                    {#await renderQR(qr) then svg}
                        {@html svg}
                    {:catch error}
                        <p>{error.message}</p>
                    {/await}
                </div>
            </div>
            <form
                class="flex flex-col items-center gap-4"
                action="/2fa/setup"
                method="post"
                novalidate
                use:form.action
            >
                <p class="text-muted-foreground text-lg">
                    Scan the QR code with your authenticator app or enter the secret key manually.
                    Then enter the code generated by your authenticator app below.
                </p>
                <div class="grid grid-cols-[auto,1fr] my-auto gap-x-6 gap-y-1.5">
                    <Label for="secret" class="justify-end items-center flex flex-row">Secret</Label
                    >
                    <Input id="secret" readonly value={secret} disabled={loading.value} />
                    <Label for="otp" class="justify-end items-center flex flex-row">OTP</Label>
                    <div>
                        <InputOTP.Root
                            maxlength={6}
                            pattern={REGEXP_ONLY_DIGITS}
                            bind:value={form.data.otp}
                            disabled={loading.value}
                        >
                            {#snippet children({ cells })}
                                {#each cells as cell (cell)}
                                    <InputOTP.Group>
                                        <InputOTP.Slot {cell} />
                                    </InputOTP.Group>
                                {/each}
                            {/snippet}
                        </InputOTP.Root>
                    </div>
                    <div class="h-6"></div>
                    <FieldError error={form.errors.otp} class="mb-0" />
                </div>
                <Button
                    size="lg"
                    class="px-16"
                    type="submit"
                    loading={processing.value}
                    disabled={loading.or(form.data.otp.length !== 6)}
                    >Submit
                </Button>
            </form>
        </div>
    </div>
</DashboardMain>
