name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.1.44
      - run: |
          bun install
          bun run build
      - uses: actions/cache@v4
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-
      - uses: php-actions/composer@v6
        with:
          php_version: '8.3'
          php_extensions: openssl
          dev: no
      - uses: up9cloud/action-rsync@master
        env:
          HOST: ${{secrets.DEPLOY_HOST}}
          PORT: ${{secrets.DEPLOY_PORT}}
          USER: ${{secrets.DEPLOY_USER}}
          KEY: ${{secrets.DEPLOY_KEY}}
          TARGET: ${{secrets.DEPLOY_PATH}}
          SOURCE: .
          ARGS: -avz --delete --exclude-from=.rsyncignore --include="**/.gitkeep"
          MODE: push
          POST_SCRIPT: |
            cd ${{secrets.DEPLOY_PATH}}
            ${{ vars.PHP_BIN }} artisan optimize
            ${{ vars.PHP_BIN }} artisan route:cache
